USE hronboarding;

CREATE TABLE `Role` (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `RoleName` VARCHAR(50) NOT NULL,
    `RoleDescription` VARCHAR(255) NULL,
    `CreateDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `LastModificationDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `PK_Role` PRIMARY KEY (`ID`),
    CONSTRAINT `UQ_Role_RoleName` UNIQUE (`RoleName`)
) ENGINE=InnoDB;

CREATE TABLE `User` (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `Username` VARCHAR(50) NOT NULL,
    `Email` VARCHAR(100) NOT NULL,
    `Password` VARCHAR(255) NOT NULL,
    `ActiveFlag` TINYINT(1) NOT NULL DEFAULT 1,             -- 1 = active, 0 = disabled
    `CreateDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `LastModificationDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `PK_User` PRIMARY KEY (`ID`),
    CONSTRAINT `UQ_User_Username` UNIQUE (`Username`),
    CONSTRAINT `UQ_User_Email` UNIQUE (`Email`)
) ENGINE=InnoDB;

CREATE TABLE `UserRole` (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `UserID` BIGINT UNSIGNED NOT NULL,
    `RoleID` BIGINT UNSIGNED NOT NULL,
    `ActiveFlag` TINYINT(1) NOT NULL DEFAULT 1,
    `CreateDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `LastModificationDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `PK_UserRole` PRIMARY KEY (`ID`),
    CONSTRAINT `FK_UserRole_User` FOREIGN KEY (`UserID`)
        REFERENCES `User`(`ID`)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT `FK_UserRole_Role` FOREIGN KEY (`RoleID`)
        REFERENCES `Role`(`ID`)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    -- prevent duplicate (User, Role) combinations
    CONSTRAINT `UQ_UserRole_User_Role` UNIQUE (`UserID`, `RoleID`)
) ENGINE=InnoDB;
